# This workflow will build the model and register to model registry.
# Note: This gihub actions job executes only for changes to specific paths. 
# Change the paths as you see fit for your use-cases.

name: Sagemaker Pipeline build SMUS project
run-name: ${{ github.actor }} is building in SMUS 🚀

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches: [ main ]
    paths:
      - 'ml_pipelines/**'
      - 'source_scripts/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ml_pipelines/**'
      - 'source_scripts/**'

permissions:
  id-token: write
  contents: read

jobs:
  GitHub-Actions-SMUS-Build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🖥️ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "👩🏻‍💻 The commit message for the event -\n ${{ github.event.head_commit.message }}"
    - uses: actions/checkout@v4
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Configure Dev Account AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: ${{secrets.PIPELINE_EXECUTION_IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./ml_pipelines/requirements.txt
    - name: Upload dataset to S3
      run: |
        python ./ml_pipelines/data/upload_s3_util.py --s3_bucket ${{secrets.ARTIFACT_BUCKET}}
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Run Sagemaker Pipeline
      run: |
        export PYTHONUNBUFFERED=TRUE
        export SAGEMAKER_PROJECT_NAME_ID="${{secrets.SAGEMAKER_PROJECT_NAME}}-${{secrets.SAGEMAKER_PROJECT_ID}}"
        python ./ml_pipelines/run_pipeline.py --module-name training.pipeline     --role-arn ${{secrets.SAGEMAKER_PIPELINE_ROLE_ARN}}     --tags '[{"Key":"sagemaker:project-name", "Value":"${{secrets.SAGEMAKER_PROJECT_NAME}}"}, {"Key":"sagemaker:project-id", "Value":"${{secrets.SAGEMAKER_PROJECT_ID}}"}, {"Key":"AmazonDataZoneDomain", "Value":"${{secrets.AMAZON_DATAZONE_DOMAIN}}"}, {"Key":"AmazonDataZoneScopeName", "Value":"${{secrets.AMAZON_DATAZONE_SCOPENAME}}"}, {"Key":"sagemaker:domain-arn", "Value":"${{secrets.SAGEMAKER_DOMAIN_ARN}}"}, {"Key":"sagemaker:space-arn", "Value":"${{secrets.SAGEMAKER_SPACE_ARN}}"}, {"Key":"AmazonDataZoneProject", "Value":"${{secrets.AMAZON_DATAZONE_PROJECT}}"}]'     --kwargs '{"region":"${{vars.REGION}}","role":"${{secrets.SAGEMAKER_PIPELINE_ROLE_ARN}}","default_bucket":"${{secrets.ARTIFACT_BUCKET}}","pipeline_name":"githubactions-${{secrets.SAGEMAKER_PROJECT_ID}}","model_package_group_name":"git-${{secrets.MODEL_PACKAGE_GROUP_NAME}}","base_job_prefix":"SMUSMLOPS"}'
        echo "🌟 Success: Create/Update of the SageMaker Pipeline and execution completed."
    - run: echo "💯 This github action job's status is ${{ job.status }}."
    
